### ISSUE TITLE
NEventStore constraint failed with MySql 8.x (works with 5.7)

### ISSUE THREAD

**Issue by gitfer** [NEventStore/NEventStore#487] opened 2020-09-18 10:01 UTC
We are considering migrating our NEventStore from RavenDB to MySQL 8.0.21 community edition.

While using your migration tool we get the following 'contraint failed error' on commits_chk_3.
![image](https://user-images.githubusercontent.com/935224/93584159-36a62680-f9a5-11ea-8c5c-92ca0edac6cc.png)

As you can see, our commitId is non-zero and it's a Guid type (NEventStore source code).

We checked NEventStore sources and the constraint comes from  https://github.com/NEventStore/NEventStore/blob/fcbf456df0654789f7b2a7709e23ccf9ea84ff73/src/NEventStore/Persistence/Sql/SqlDialects/MySqlStatements.resx#L128 while CommitId being a Guid type comes from NEventStore sources (class CommitAttempt).

We obviously get the same error even in our application and not just on the migration tool.

We couldn't quite understand what's happening...by your documentation it looks like our MySQL version (which is the latest available) should work...

Thank you for your time

**Comment by AGiorgetti** [comment] 2020-12-10 12:29
I can confirm there are issues with MySql 8.x, it works in 5.7.

This is the structure that is created in 8.x, the issue is with the Guid field, have to investigare.

CREATE TABLE `Commits` (
   `BucketId` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
   `StreamId` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
   `StreamIdOriginal` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
   `StreamRevision` int NOT NULL,
   `Items` int NOT NULL,
   `CommitId` binary(16) NOT NULL,
   `CommitSequence` int NOT NULL,
   `CommitStamp` bigint NOT NULL,
   `CheckpointNumber` bigint NOT NULL AUTO_INCREMENT,
   `Headers` blob,
   `Payload` mediumblob NOT NULL,
   PRIMARY KEY (`CheckpointNumber`),
   UNIQUE KEY `IX_Commits` (`BucketId`,`StreamId`,`CommitSequence`),
   UNIQUE KEY `IX_Commits_CommitId` (`BucketId`,`StreamId`,`CommitId`),
   UNIQUE KEY `IX_Commits_Revisions` (`BucketId`,`StreamId`,`StreamRevision`,`Items`),
   KEY `IX_Commits_Stamp` (`CommitStamp`),
   CONSTRAINT `Commits_chk_1` CHECK ((`StreamRevision` > 0)),
   CONSTRAINT `Commits_chk_2` CHECK ((`Items` > 0)),
   CONSTRAINT `Commits_chk_3` CHECK ((`CommitId` <> 0)),
   CONSTRAINT `Commits_chk_4` CHECK ((`CommitSequence` > 0))
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

**Comment by AGiorgetti** [comment] 2023-07-31 09:13
PR merged

**Closed by AGiorgetti** 2023-07-31 09:13 UTC
Labels: Bug, SQL Provider
