### ISSUE TITLE
OptimisticEventStore doesn't throw ConcurrencyException if first two events on a stream race

### ISSUE THREAD

**Issue by AndyAtAsos** [NEventStore/NEventStore#415] opened 2015-09-08 11:41 UTC
During performance testing we noticed that if the first two events for a stream occur simultaneously, the concurrency check is bypassed and a dirty read is then saved.

Scenario 1
1. [Thread A] The aggregate is loaded and no events are found.
2. [Thread B] Another thread then writes to the stream at Revision 1.
3. [Thread A] The aggregate modifies data, adds an event and then saves.
4. [Thread A] The aggregate saves stale data at revision 2. The concurrency exception is not thrown.

If you repeat the test with an event having already been persisted:
Scenario 2
1. [Thread A] The aggregate is loaded and an event is found. The aggregate has 1 event.
2. [Thread B] Another thread then writes to the stream at Revision 2.
3. [Thread A] The aggregate modifies data, adds an event and then saves.
4. [Thread A] A concurrency exception is thrown. 

We believe the error is in NEventStore.OptimisticEventStore when the aggregate is being saved:

public virtual IEventStream OpenStream(string bucketId, string streamId, int minRevision, int maxRevision)
        {
            // The offending line follows
            maxRevision = maxRevision <= 0 ? int.MaxValue : maxRevision;
            ....
        }

For the Scenario 1, it is being called with minRevision = 0, maxRevision = 0.
It is then opening the whole of the stream and appending [stale data] to the stream.

During Scenario 2, the dirty read is saved with minRevision = 1, maxRevision = 1. The concurrency exception is then thrown.

Using NEventStore 5.2.0 with Mongo.

**Comment by AGiorgetti** [comment] 2016-01-12 11:47
Hi, can you help us providing a test case to reproduce the issue?

**Comment by alkampfergit** [comment] 2016-07-12 12:20
Since there are not test case to reproduce the issue we close the issue. The issue will be reopened if a test case will be given to reproduce the issue

**Closed by alkampfergit** 2016-07-12 12:20 UTC
