### ISSUE TITLE
Corrupt event store

### ISSUE THREAD

**Issue by UnclearMaker** [NEventStore/NEventStore#456] opened 2017-04-21 13:54 UTC
We have been receiving unexpected optimistic concurrency exceptions ('NEventStore.ConcurrencyException') when attempting to add and commit new events using NEventStore.IEventStream methods:

```
void Add(EventMessage uncommittedEvent);
void CommitChanges(Guid commitId);
```

Or log files show (example):

> The underlying stream '4d3b7950-a561-5da5-bdbc-726f238655b4' has changed since the last known commit, refreshing the stream.

followed by:

> An unhandled exception has occurred: Exception of type 'NEventStore.ConcurrencyException' was thrown.

We are fairly certain there are no other events being written at the time the exception occurs.

Looking in our MSSQL Commits table, the stream records in question have duplicate BucketId/StreamId/CommitSequence entries.

We've found that our Commits table has the following indexes missing (we're not sure why):

```
CREATE UNIQUE NONCLUSTERED INDEX [IX_Commits_CommitSequence] ON Commits (BucketId, StreamId, CommitSequence);
CREATE UNIQUE NONCLUSTERED INDEX [IX_Commits_CommitId] ON [dbo].[Commits] ([BucketId], [StreamId], [CommitId]);
CREATE UNIQUE NONCLUSTERED INDEX [IX_Commits_Revisions] ON [dbo].[Commits] ([BucketId], [StreamId], [StreamRevision], [Items]);
```
The first index implies that we should not have duplicate BucketId/StreamId/CommitSequence entries. When we manually correct the CommitSequence values within the streams to ensure uniqueness, we no longer receive the concurrency exception.

Ignoring the fact that these records are being created somehow, we need to urgently update the broken records so that we no longer receive the concurrency exceptions. Then we intend to create the above indexes so that we can investigate the reason why they are being created in the first place.

From what we can tell, the only way to fix the broken records is to sort them by CheckpointNumber and then set the CommitSequence integers to be the ordinal row number positions.

Is this approach sound? If not, can anyone suggest an alternative solution?

In addition, can anyone explain what CommitSequence & StreamRevision mean / are for? And whether the CheckpointSequence orders the commits within an aggregate?

Thanks!

**Comment by fschmied** [comment] 2017-04-26 18:16
It is my understanding that CommitSequence exists primarily for catching concurrent writes on the same stream, by means of that BucketId/StreamId/CommitSequence unique index. So if that's removed, it's possible for two concurrent transactions to write new commits without seeing those written by the other.

StreamRevision is used for querying via the event-based stream version, IIRC. Since commits can contain multiple events, this can be different from the CommitSequence. I guess if the index was disabled and concurrent commits occurred, this would also be wrong and in need to be fixed. (After reordering, calculate the new values by using the Items column.)

CheckpointSequence imposes a global ordering on the commits that is usually consistent with the stream (aggregate) ordering. (If it wasn't, it wouldn't work for building read models, which is what it's meant for.) However, if you had concurrent transactions that were not caught, there is no defined order between concurrently written commits.

Best regards,
Fabian 

----- Ursprüngliche Nachricht -----
Von: "mlaurence" <notifications@github.com>
Gesendet: ‎21.‎04.‎2017 15:54
An: "NEventStore/NEventStore" <NEventStore@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [NEventStore/NEventStore] Fixing a corrupt event store (#456)

We have been receiving unexpected optimistic concurrency exceptions ('NEventStore.ConcurrencyException') when attempting to add and commit new events using NEventStore.IEventStream methods:
void Add(EventMessage uncommittedEvent);
void CommitChanges(Guid commitId);
Or log files show (example):
The underlying stream '4d3b7950-a561-5da5-bdbc-726f238655b4' has changed since the last known commit, refreshing the stream.
followed by:
An unhandled exception has occurred: Exception of type 'NEventStore.ConcurrencyException' was thrown.
We are fairly certain there are no other events being written at the time the exception occurs.
Looking in our MSSQL Commits table, the stream records in question have duplicate BucketId/StreamId/CommitSequence entries.
We've found that our Commits table has the following indexes missing (we're not sure why):
CREATE UNIQUE NONCLUSTERED INDEX [IX_Commits_CommitSequence] ON Commits (BucketId, StreamId, CommitSequence);
CREATE UNIQUE NONCLUSTERED INDEX [IX_Commits_CommitId] ON [dbo].[Commits] ([BucketId], [StreamId], [CommitId]);
CREATE UNIQUE NONCLUSTERED INDEX [IX_Commits_Revisions] ON [dbo].[Commits] ([BucketId], [StreamId], [StreamRevision], [Items]);
The first index implies that we should not have duplicate BucketId/StreamId/CommitSequence entries. When we manually correct the CommitSequence values within the streams to ensure uniqueness, we no longer receive the concurrency exception.
Ignoring the fact that these records are being created somehow, we need to urgently update the broken records so that we no longer receive the concurrency exceptions. Then we intend to create the above indexes so that we can investigate the reason why they are being created in the first place.
From what we can tell, the only way to fix the broken records is to sort them by CheckpointNumber and then set the CommitSequence integers to be the ordinal row number positions.
Is this approach sound? If not, can anyone suggest an alternative solution?
In addition, can anyone explain what CommitSequence & StreamRevision mean / are for? And whether the CheckpointSequence orders the commits within an aggregate?
Thanks!

**Comment by AGiorgetti** [comment] 2019-07-14 17:29
Closing the issue because everything said by @fschmied is correct and I actually cannot reproduce the problem od the missing indexes.

If someone has a similar problem (the missing indexes that caused the wrong writes) we can reopen this.

**Closed by AGiorgetti** 2019-07-14 17:29 UTC
